// Static product data — used when backend is unavailable

export const CATEGORIES = [
    { _id: 'cat-electronics', name: 'Electronics', slug: 'electronics' },
    { _id: 'cat-fashion-men', name: "Men's Fashion", slug: 'mens-fashion' },
    { _id: 'cat-fashion-women', name: "Women's Fashion", slug: 'womens-fashion' },
    { _id: 'cat-food', name: 'Food & Grocery', slug: 'food-grocery' },
    { _id: 'cat-home', name: 'Home & Living', slug: 'home-living' },
    { _id: 'cat-beauty', name: 'Beauty & Health', slug: 'beauty-health' },
];

export const MOCK_PRODUCTS = [
    // ── Electronics ──
    {
        _id: 'prod-001',
        name: 'Samsung Galaxy A55 5G',
        slug: 'samsung-galaxy-a55-5g',
        description: 'Experience blazing-fast 5G connectivity with the Samsung Galaxy A55. Features a stunning 6.6-inch Super AMOLED display with 120Hz refresh rate, 50MP triple camera system with OIS, and a powerful Exynos 1480 processor. With 8GB RAM and 256GB storage, this phone handles multitasking with ease. The 5000mAh battery with 25W fast charging keeps you powered all day.',
        tagline: 'Blazing fast 5G smartphone with pro-grade cameras',
        shortDescription: 'Blazing fast 5G smartphone with pro-grade cameras',
        price: 34999,
        comparePrice: 38999,
        originalPrice: 38999,
        discount: 10,
        stock: 25,
        quantity: 25,
        thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800',
            'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?q=80&w=800',
            'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800',
        ],
        category: { _id: 'cat-electronics', name: 'Electronics' },
        rating: 4.7,
        reviewCount: 128,
        salesCount: 340,
        totalSold: 340,
        viewCount: 2100,
        sku: 'SAM-A55-256-BLK',
        tags: ['samsung', '5g', 'smartphone', 'android'],
        colors: ['Midnight Black', 'Awesome Iceblue', 'Awesome Navy'],
        isFeatured: true,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-002',
        name: 'JBL Tune 770NC Wireless Headphones',
        slug: 'jbl-tune-770nc-wireless',
        description: 'Immerse yourself in music with JBL Tune 770NC featuring Adaptive Noise Cancelling technology. Enjoy up to 70 hours of playtime with ANC off, or 44 hours with ANC on. The foldable design makes it easy to carry anywhere. Multipoint connection lets you connect to two devices simultaneously.',
        tagline: 'Pure Bass sound with 70-hour battery life',
        shortDescription: 'Pure Bass sound with 70-hour battery life',
        price: 8499,
        comparePrice: 11999,
        originalPrice: 11999,
        discount: 29,
        stock: 40,
        quantity: 40,
        thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800',
            'https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=800',
        ],
        category: { _id: 'cat-electronics', name: 'Electronics' },
        rating: 4.5,
        reviewCount: 89,
        salesCount: 210,
        totalSold: 210,
        viewCount: 1450,
        sku: 'JBL-T770NC-BLK',
        tags: ['jbl', 'headphones', 'wireless', 'anc'],
        colors: ['Black', 'White', 'Blue'],
        isFeatured: true,
        isNewProduct: true,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-003',
        name: 'Smart Watch Ultra Pro',
        slug: 'smart-watch-ultra-pro',
        description: 'Track your fitness and stay connected with the Smart Watch Ultra Pro. Features heart rate monitoring, SpO2 tracking, GPS, and 50+ sport modes. The always-on AMOLED display with 1.96 inch screen delivers crisp visuals. IP68 waterproof rating ensures it survives any adventure. Compatible with both Android and iOS.',
        tagline: 'Your ultimate fitness & lifestyle companion',
        shortDescription: 'Your ultimate fitness & lifestyle companion',
        price: 7999,
        comparePrice: 12000,
        originalPrice: 12000,
        discount: 33,
        stock: 18,
        quantity: 18,
        thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800',
            'https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=800',
        ],
        category: { _id: 'cat-electronics', name: 'Electronics' },
        rating: 4.3,
        reviewCount: 62,
        salesCount: 145,
        totalSold: 145,
        viewCount: 980,
        sku: 'SWT-ULTRA-PRO-BLK',
        tags: ['smartwatch', 'fitness', 'gps', 'amoled'],
        colors: ['Black', 'Silver', 'Gold'],
        isFeatured: false,
        isNewProduct: true,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-004',
        name: 'TWS Wireless Earbuds Pro',
        slug: 'tws-wireless-earbuds-pro',
        description: 'Experience studio-quality sound in a truly wireless form. These TWS earbuds feature Active Noise Cancellation, 30-hour total playtime with the charging case, and IPX5 water resistance. The ergonomic design ensures a comfortable fit for long listening sessions. Touch controls make it easy to manage calls and music.',
        tagline: 'Studio sound, totally wire-free',
        shortDescription: 'Studio sound, totally wire-free',
        price: 2199,
        comparePrice: 3500,
        originalPrice: 3500,
        discount: 37,
        stock: 55,
        quantity: 55,
        thumbnail: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?q=80&w=800',
            'https://images.unsplash.com/photo-1608156639585-b3a032ef9689?q=80&w=800',
        ],
        category: { _id: 'cat-electronics', name: 'Electronics' },
        rating: 4.1,
        reviewCount: 174,
        salesCount: 520,
        totalSold: 520,
        viewCount: 3200,
        sku: 'TWS-PRO-WHT',
        tags: ['earbuds', 'tws', 'wireless', 'anc'],
        colors: ['White', 'Black'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    // ── Men's Fashion ──
    {
        _id: 'prod-005',
        name: 'Premium Cotton Panjabi',
        slug: 'premium-cotton-panjabi',
        description: "Crafted from 100% premium cotton, this traditional Panjabi combines comfort with elegance. The fine thread work on the collar and cuffs adds a sophisticated touch. Perfect for Eid, weddings, and festive occasions. Machine washable and easy to maintain. Available in multiple sizes and colors.",
        tagline: 'Elegance woven in every thread',
        shortDescription: 'Elegance woven in every thread',
        price: 1199,
        comparePrice: 1800,
        originalPrice: 1800,
        discount: 33,
        stock: 60,
        quantity: 60,
        thumbnail: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4576?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1594938298603-c8148c4b4576?q=80&w=800',
            'https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-men', name: "Men's Fashion" },
        rating: 4.6,
        reviewCount: 95,
        salesCount: 280,
        totalSold: 280,
        viewCount: 1800,
        sku: 'PAN-COT-M-WHT',
        tags: ['panjabi', 'eid', 'cotton', 'traditional'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Off-White', 'Light Blue', 'Mint Green'],
        isFeatured: true,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-006',
        name: 'Slim Fit Casual T-Shirt (Pack of 3)',
        slug: 'slim-fit-casual-tshirt-pack-3',
        description: 'Get more value with this pack of 3 premium cotton slim-fit t-shirts. Each t-shirt is made from 180 GSM bio-washed cotton for a soft feel against the skin. The slim-fit design gives a modern look. Round neck and short sleeves make it a versatile wardrobe essential. Colors are vibrant and long-lasting.',
        tagline: 'Comfort meets style — pack of 3',
        shortDescription: 'Comfort meets style — pack of 3',
        price: 849,
        comparePrice: 1200,
        originalPrice: 1200,
        discount: 29,
        stock: 80,
        quantity: 80,
        thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800',
            'https://images.unsplash.com/photo-1503341504253-dff4815485f1?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-men', name: "Men's Fashion" },
        rating: 4.4,
        reviewCount: 218,
        salesCount: 650,
        totalSold: 650,
        viewCount: 4100,
        sku: 'TSH-SLM-PK3-M',
        tags: ['t-shirt', 'casual', 'cotton', 'pack'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Multicolor (3 pcs)'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-007',
        name: "Men's Slim Fit Denim Jeans",
        slug: 'mens-slim-fit-denim-jeans',
        description: "These premium slim-fit denim jeans are crafted from high-quality stretchable denim fabric that offers both comfort and style. The five-pocket design with reinforced stitching ensures durability. Suitable for casual outings, college, and semi-formal occasions. Available in multiple washes — dark blue, mid blue, and black.",
        tagline: 'Denim that moves with you',
        shortDescription: 'Denim that moves with you',
        price: 1799,
        comparePrice: 2500,
        originalPrice: 2500,
        discount: 28,
        stock: 45,
        quantity: 45,
        thumbnail: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=800',
            'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-men', name: "Men's Fashion" },
        rating: 4.3,
        reviewCount: 143,
        salesCount: 390,
        totalSold: 390,
        viewCount: 2600,
        sku: 'JNS-SLM-M-DBL',
        tags: ['jeans', 'denim', 'slim-fit', 'men'],
        sizes: ['30', '32', '34', '36', '38'],
        colors: ['Dark Blue', 'Mid Blue', 'Black'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-008',
        name: "Men's Formal Oxford Shirt",
        slug: 'mens-formal-oxford-shirt',
        description: 'Look sharp and professional with this premium Oxford cotton formal shirt. The fabric is wrinkle-resistant and breathable, making it ideal for long office hours. The classic button-down collar and slim-fit cut create a polished appearance. Easy-care fabric requires minimal ironing. Perfect for office, meetings, and formal events.',
        tagline: 'Dress sharp, think sharp',
        shortDescription: 'Dress sharp, think sharp',
        price: 1099,
        comparePrice: 1600,
        originalPrice: 1600,
        discount: 31,
        stock: 50,
        quantity: 50,
        thumbnail: 'https://images.unsplash.com/photo-1602810316498-ab67cf68c8e1?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1602810316498-ab67cf68c8e1?q=80&w=800',
            'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-men', name: "Men's Fashion" },
        rating: 4.5,
        reviewCount: 76,
        salesCount: 195,
        totalSold: 195,
        viewCount: 1350,
        sku: 'SHT-OXF-M-WHT',
        tags: ['shirt', 'formal', 'office', 'oxford'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Light Blue', 'Light Pink', 'Grey'],
        isFeatured: false,
        isNewProduct: true,
        isOnSale: true,
        status: 'active',
    },
    // ── Women's Fashion ──
    {
        _id: 'prod-009',
        name: 'Handloom Silk Saree',
        slug: 'handloom-silk-saree',
        description: 'This exquisite handloom silk saree is a masterpiece of traditional craftsmanship. Woven by skilled artisans, the saree features intricate zari border work and a rich pallu. The pure silk fabric drapes beautifully and has a natural lustrous sheen. Comes with matching blouse piece. Perfect for weddings, festivals, and special occasions.',
        tagline: 'Tradition redefined in pure silk',
        shortDescription: 'Tradition redefined in pure silk',
        price: 4499,
        comparePrice: 6500,
        originalPrice: 6500,
        discount: 31,
        stock: 20,
        quantity: 20,
        thumbnail: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800',
            'https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-women', name: "Women's Fashion" },
        rating: 4.8,
        reviewCount: 54,
        salesCount: 110,
        totalSold: 110,
        viewCount: 890,
        sku: 'SAR-SLK-HND-RED',
        tags: ['saree', 'silk', 'handloom', 'wedding'],
        colors: ['Red & Gold', 'Blue & Silver', 'Green & Gold', 'Maroon & Gold'],
        isFeatured: true,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-010',
        name: 'Printed Cotton Kurti',
        slug: 'printed-cotton-kurti',
        description: 'This beautiful printed cotton kurti is the perfect blend of comfort and contemporary style. Made from 100% pure cotton, it keeps you cool in warm weather. The vibrant block print design adds a touch of ethnic charm. The knee-length cut with side slits makes it versatile — pair with leggings, jeans, or palazzos.',
        tagline: 'Ethnic charm, everyday comfort',
        shortDescription: 'Ethnic charm, everyday comfort',
        price: 949,
        comparePrice: 1400,
        originalPrice: 1400,
        discount: 32,
        stock: 70,
        quantity: 70,
        thumbnail: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800',
            'https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-women', name: "Women's Fashion" },
        rating: 4.4,
        reviewCount: 187,
        salesCount: 480,
        totalSold: 480,
        viewCount: 3100,
        sku: 'KUR-COT-PRT-M',
        tags: ['kurti', 'cotton', 'ethnic', 'printed'],
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Indigo Blue', 'Brick Red', 'Mustard Yellow', 'Olive Green'],
        isFeatured: false,
        isNewProduct: true,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-011',
        name: 'Ladies Leather Handbag',
        slug: 'ladies-leather-handbag',
        description: 'Elevate your style with this premium PU leather handbag. Featuring a spacious main compartment with multiple inner pockets for organized storage. The sturdy metal zipper and reinforced handles ensure long-lasting durability. The adjustable shoulder strap makes it comfortable to carry. A perfect everyday bag for work, shopping, or casual outings.',
        tagline: 'Carry everything in style',
        shortDescription: 'Carry everything in style',
        price: 2199,
        comparePrice: 3500,
        originalPrice: 3500,
        discount: 37,
        stock: 30,
        quantity: 30,
        thumbnail: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800',
            'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800',
        ],
        category: { _id: 'cat-fashion-women', name: "Women's Fashion" },
        rating: 4.2,
        reviewCount: 112,
        salesCount: 260,
        totalSold: 260,
        viewCount: 1700,
        sku: 'HBG-PU-LDY-BLK',
        tags: ['handbag', 'leather', 'ladies', 'purse'],
        colors: ['Black', 'Brown', 'Burgundy', 'Tan'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    // ── Food & Grocery ──
    {
        _id: 'prod-012',
        name: 'Sundarbans Pure Honey 1kg',
        slug: 'sundarbans-pure-honey-1kg',
        description: 'Sourced directly from the beekeepers of the Sundarbans mangrove forest, this raw honey is 100% pure and unprocessed. Rich in antioxidants, enzymes, and natural minerals. No added sugar, preservatives, or artificial colors. The unique floral notes come from the diverse flora of the Sundarbans. Lab-tested for purity and quality. Ideal for daily consumption, cooking, and home remedies.',
        tagline: 'Pure goodness straight from the Sundarbans',
        shortDescription: 'Pure goodness straight from the Sundarbans',
        price: 849,
        comparePrice: 1200,
        originalPrice: 1200,
        discount: 29,
        stock: 100,
        quantity: 100,
        thumbnail: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?q=80&w=800',
            'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=800',
        ],
        category: { _id: 'cat-food', name: 'Food & Grocery' },
        rating: 4.9,
        reviewCount: 324,
        salesCount: 890,
        totalSold: 890,
        viewCount: 5600,
        sku: 'HNY-SND-1KG',
        tags: ['honey', 'pure', 'sundarbans', 'natural', 'organic'],
        isFeatured: true,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-013',
        name: 'Cold-Pressed Mustard Oil 2L',
        slug: 'cold-pressed-mustard-oil-2l',
        description: 'Our cold-pressed mustard oil is extracted using traditional stone-mill method, preserving all the natural nutrients and pungent flavor. Rich in omega-3 fatty acids, monounsaturated fats, and Vitamin E. The cold-press process ensures no heat is applied, maintaining the oil\'s natural antioxidants. Free from additives and preservatives. Ideal for cooking, marinating, and traditional hair care.',
        tagline: 'The purest oil for the healthiest cooking',
        shortDescription: 'The purest oil for the healthiest cooking',
        price: 319,
        comparePrice: 450,
        originalPrice: 450,
        discount: 29,
        stock: 150,
        quantity: 150,
        thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=800',
        ],
        category: { _id: 'cat-food', name: 'Food & Grocery' },
        rating: 4.6,
        reviewCount: 198,
        salesCount: 560,
        totalSold: 560,
        viewCount: 3400,
        sku: 'OIL-MUS-2L',
        tags: ['mustard oil', 'cold-pressed', 'cooking', 'pure'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-014',
        name: 'Premium Basmati Rice 5kg',
        slug: 'premium-basmati-rice-5kg',
        description: 'Long-grain premium basmati rice with a natural fragrance that fills your kitchen as it cooks. Each grain is aged for at least 2 years for enhanced aroma and non-sticky texture. Perfect for biryani, pulao, and everyday meals. Thoroughly cleaned and processed to remove impurities. A household staple that elevates every meal.',
        tagline: 'The fragrance that makes every meal special',
        shortDescription: 'The fragrance that makes every meal special',
        price: 649,
        comparePrice: 850,
        originalPrice: 850,
        discount: 24,
        stock: 200,
        quantity: 200,
        thumbnail: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800',
            'https://images.unsplash.com/photo-1536304993881-ff86e0c9b7b8?q=80&w=800',
        ],
        category: { _id: 'cat-food', name: 'Food & Grocery' },
        rating: 4.5,
        reviewCount: 256,
        salesCount: 720,
        totalSold: 720,
        viewCount: 4200,
        sku: 'RCE-BAS-5KG',
        tags: ['rice', 'basmati', 'premium', 'biryani'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-015',
        name: 'Organic Green Tea 100 Bags',
        slug: 'organic-green-tea-100-bags',
        description: 'Start your wellness journey with our premium organic green tea sourced from high-altitude tea gardens. Each tea bag is filled with carefully selected young tea leaves, ensuring a rich, smooth flavor without bitterness. Packed with antioxidants and catechins to support metabolism and immunity. No artificial flavors or colors. Individually foil-wrapped bags preserve freshness.',
        tagline: 'Nature\'s finest brew for a healthier you',
        shortDescription: "Nature's finest brew for a healthier you",
        price: 449,
        comparePrice: 650,
        originalPrice: 650,
        discount: 31,
        stock: 120,
        quantity: 120,
        thumbnail: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=800',
            'https://images.unsplash.com/photo-1582793988951-9aed5509eb97?q=80&w=800',
        ],
        category: { _id: 'cat-food', name: 'Food & Grocery' },
        rating: 4.7,
        reviewCount: 145,
        salesCount: 410,
        totalSold: 410,
        viewCount: 2700,
        sku: 'TEA-GRN-100B',
        tags: ['green tea', 'organic', 'healthy', 'antioxidant'],
        isFeatured: false,
        isNewProduct: true,
        isOnSale: true,
        status: 'active',
    },
    // ── Home & Living ──
    {
        _id: 'prod-016',
        name: 'Ceramic Dinner Set 24 Pieces',
        slug: 'ceramic-dinner-set-24-pieces',
        description: 'Transform your dining experience with this elegant 24-piece ceramic dinner set. Includes 6 dinner plates (10.5"), 6 side plates (7.5"), 6 bowls, and 6 mugs. Made from high-quality porcelain with chip-resistant glaze. Dishwasher and microwave safe. The classic white design with subtle embossed pattern complements any table setting.',
        tagline: 'Every meal deserves a beautiful table',
        shortDescription: 'Every meal deserves a beautiful table',
        price: 2799,
        comparePrice: 4500,
        originalPrice: 4500,
        discount: 38,
        stock: 25,
        quantity: 25,
        thumbnail: 'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?q=80&w=800',
            'https://images.unsplash.com/photo-1584346133934-a3afd13a1f60?q=80&w=800',
        ],
        category: { _id: 'cat-home', name: 'Home & Living' },
        rating: 4.4,
        reviewCount: 83,
        salesCount: 170,
        totalSold: 170,
        viewCount: 1200,
        sku: 'DNS-CRM-24PC-WHT',
        tags: ['dinner set', 'ceramic', 'porcelain', 'kitchenware'],
        colors: ['White', 'Ivory'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-017',
        name: 'King Size Cotton Bedsheet Set',
        slug: 'king-size-cotton-bedsheet-set',
        description: 'Sleep in luxury with this premium 100% cotton bedsheet set. The 300 thread count fabric is incredibly soft and breathable, ensuring a comfortable sleep throughout the year. Set includes 1 fitted sheet, 1 flat sheet, and 2 pillow covers. Deep pocket design fits mattresses up to 14" thick. Fade-resistant and machine washable.',
        tagline: 'Because you deserve the best sleep',
        shortDescription: 'Because you deserve the best sleep',
        price: 1499,
        comparePrice: 2200,
        originalPrice: 2200,
        discount: 32,
        stock: 40,
        quantity: 40,
        thumbnail: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=800',
            'https://images.unsplash.com/photo-1618677831708-0e7fda3148b4?q=80&w=800',
        ],
        category: { _id: 'cat-home', name: 'Home & Living' },
        rating: 4.6,
        reviewCount: 134,
        salesCount: 310,
        totalSold: 310,
        viewCount: 2100,
        sku: 'BDS-KNG-COT-WHT',
        tags: ['bedsheet', 'cotton', 'king size', 'bedroom'],
        colors: ['White', 'Cream', 'Sky Blue', 'Mint'],
        isFeatured: true,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-018',
        name: 'LED Desk Lamp with Wireless Charger',
        slug: 'led-desk-lamp-wireless-charger',
        description: 'This multi-functional LED desk lamp combines powerful lighting with Qi wireless charging technology. Features 5 color modes (warm, neutral, cool, reading, night) and 10 brightness levels. The built-in 10W wireless charger pad keeps your phone charged. USB-A port for additional device charging. Memory function saves your last settings. Flexible gooseneck for precise positioning.',
        tagline: 'Light up your workspace, charge your world',
        shortDescription: 'Light up your workspace, charge your world',
        price: 1899,
        comparePrice: 2800,
        originalPrice: 2800,
        discount: 32,
        stock: 35,
        quantity: 35,
        thumbnail: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800',
            'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=800',
        ],
        category: { _id: 'cat-home', name: 'Home & Living' },
        rating: 4.5,
        reviewCount: 91,
        salesCount: 220,
        totalSold: 220,
        viewCount: 1580,
        sku: 'LMP-LED-DSK-WLC',
        tags: ['desk lamp', 'led', 'wireless charger', 'office'],
        colors: ['White', 'Black'],
        isFeatured: false,
        isNewProduct: true,
        isOnSale: true,
        status: 'active',
    },
    // ── Beauty & Health ──
    {
        _id: 'prod-019',
        name: 'Neem & Turmeric Herbal Face Wash',
        slug: 'neem-turmeric-herbal-face-wash',
        description: 'Harness the power of nature with this Neem & Turmeric face wash. The unique formula combines the antibacterial properties of neem with the brightening effects of turmeric. Gently removes dirt, oil, and impurities without stripping natural moisture. Suitable for all skin types including sensitive skin. Free from sulfates, parabens, and artificial fragrances. Regular use helps reduce acne, dark spots, and uneven skin tone.',
        tagline: 'Ancient herbs, modern glow',
        shortDescription: 'Ancient herbs, modern glow',
        price: 379,
        comparePrice: 550,
        originalPrice: 550,
        discount: 31,
        stock: 90,
        quantity: 90,
        thumbnail: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1556228578-8c89e6adf883?q=80&w=800',
            'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800',
        ],
        category: { _id: 'cat-beauty', name: 'Beauty & Health' },
        rating: 4.6,
        reviewCount: 267,
        salesCount: 740,
        totalSold: 740,
        viewCount: 4800,
        sku: 'FCW-NEM-TUR-100',
        tags: ['face wash', 'neem', 'turmeric', 'herbal', 'skincare'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
    {
        _id: 'prod-020',
        name: 'Argan & Coconut Hair Oil 200ml',
        slug: 'argan-coconut-hair-oil-200ml',
        description: 'Give your hair the nourishment it deserves with this luxurious blend of Moroccan Argan oil and pure Coconut oil. Rich in Vitamin E, fatty acids, and antioxidants, this hair oil deeply conditions and strengthens hair from roots to tips. Reduces frizz, adds shine, and promotes healthy hair growth. Lightweight, non-greasy formula absorbs quickly. Suitable for all hair types — dry, damaged, colored, or normal.',
        tagline: 'Liquid gold for your gorgeous hair',
        shortDescription: 'Liquid gold for your gorgeous hair',
        price: 519,
        comparePrice: 750,
        originalPrice: 750,
        discount: 31,
        stock: 75,
        quantity: 75,
        thumbnail: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=800',
        images: [
            'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=800',
            'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800',
        ],
        category: { _id: 'cat-beauty', name: 'Beauty & Health' },
        rating: 4.7,
        reviewCount: 189,
        salesCount: 520,
        totalSold: 520,
        viewCount: 3300,
        sku: 'HRO-ARG-CCN-200',
        tags: ['hair oil', 'argan', 'coconut', 'nourishing'],
        isFeatured: false,
        isNewProduct: false,
        isOnSale: true,
        status: 'active',
    },
];

// Filter + sort + paginate helper
export function filterProducts(params: {
    category?: string;
    sort?: string;
    page?: number;
    limit?: number;
    minPrice?: number;
    maxPrice?: number;
    search?: string;
    isFeatured?: boolean;
    isNewProduct?: boolean;
    inStock?: boolean;
    id?: string;
}) {
    let results = [...MOCK_PRODUCTS];

    if (params.category) {
        results = results.filter(p =>
            p.category._id === params.category ||
            p.category.name.toLowerCase() === params.category!.toLowerCase()
        );
    }
    if (params.isFeatured) results = results.filter(p => p.isFeatured);
    if (params.isNewProduct) results = results.filter(p => p.isNewProduct);
    if (params.inStock) results = results.filter(p => p.stock > 0);
    if (params.minPrice !== undefined) results = results.filter(p => p.price >= params.minPrice!);
    if (params.maxPrice !== undefined) results = results.filter(p => p.price <= params.maxPrice!);
    if (params.search) {
        const q = params.search.toLowerCase();
        results = results.filter(p =>
            p.name.toLowerCase().includes(q) ||
            (p.tags || []).some((t: string) => t.includes(q))
        );
    }

    switch (params.sort) {
        case 'price-low': results.sort((a, b) => a.price - b.price); break;
        case 'price-high': results.sort((a, b) => b.price - a.price); break;
        case 'rating': results.sort((a, b) => b.rating - a.rating); break;
        case 'bestselling': results.sort((a, b) => b.salesCount - a.salesCount); break;
        case 'name-asc': results.sort((a, b) => a.name.localeCompare(b.name)); break;
        case 'newest': results.sort((a, b) => (b.isNewProduct ? 1 : 0) - (a.isNewProduct ? 1 : 0)); break;
        default: break;
    }

    const page = params.page || 1;
    const limit = params.limit || 12;
    const total = results.length;
    const totalPages = Math.ceil(total / limit);
    const data = results.slice((page - 1) * limit, page * limit);

    return {
        data,
        meta: { page, limit, total, totalPages },
    };
}
